// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net.Kidd.Habitizer.Persistence.DbContext;

#nullable disable

namespace Net.Kidd.Habitizer.Persistence.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portfolio")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Net.Kidd.Habitizer.Persistence.Account.AccountDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Name")
                        .IsUnique();

                    b.ToTable("Accounts", "portfolio");
                });

            modelBuilder.Entity("Net.Kidd.Habitizer.Persistence.Instrument.InstrumentDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Isin")
                        .IsUnique();

                    b.ToTable("Instruments", "portfolio");
                });

            modelBuilder.Entity("Net.Kidd.Habitizer.Persistence.Position.PositionDbo", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("NetSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferencePrice_Currency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReferencePrice_Currency");

                    b.Property<decimal?>("ReferencePrice_CurrencySpot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferencePrice_Exchange")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReferencePrice_Exchange");

                    b.Property<decimal?>("ReferencePrice_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnrealisedAverageCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnrealisedProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnrealisedProfitPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AccountId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Positions", "portfolio");
                });

            modelBuilder.Entity("Net.Kidd.Habitizer.Persistence.Source.SourceDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sources", "portfolio");
                });

            modelBuilder.Entity("Net.Kidd.Habitizer.Persistence.Account.AccountDbo", b =>
                {
                    b.HasOne("Net.Kidd.Habitizer.Persistence.Source.SourceDbo", "Source")
                        .WithMany("Accounts")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Net.Kidd.Habitizer.Persistence.Position.PositionDbo", b =>
                {
                    b.HasOne("Net.Kidd.Habitizer.Persistence.Account.AccountDbo", "Account")
                        .WithMany("Positions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Net.Kidd.Habitizer.Persistence.Instrument.InstrumentDbo", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Net.Kidd.Habitizer.Persistence.Account.AccountDbo", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Net.Kidd.Habitizer.Persistence.Source.SourceDbo", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
