name: net-kidd-habitizer

services:
  syncdaemon:
    image: "${SYNCDAEMON_IMAGE_TAG:-net-kidd-habitizer-syncdaemon:latest}"
    env_file:
      - .env
    networks:
      - habitizer-network
    volumes:
      - net-kidd-habitizer-syncdaemon-logs:/app/publish/logs
    restart: unless-stopped

networks:
  habitizer-network:
    name: habitizer-network

volumes:
  net-kidd-habitizer-syncdaemon-logs:
    name: net-kidd-habitizer-syncdaemon-logs
