name: net-kidd-habitizer

services:
  syncdaemon:
    build:
      context: ../..
      dockerfile: cicd/apps/Dockerfile.syncdaemon
    image: net-kidd-habitizer-syncdaemon:latest
    env_file:
      - .env.local
    networks:
      - habitizer-network
      - mssql-network
    volumes:
      - net-kidd-habitizer-syncdaemon-logs:/app/publish/logs
    restart: unless-stopped

networks:
  habitizer-network:
    name: habitizer-network
  mssql-network:
    name: mssql-network
    external: true

volumes:
  net-kidd-habitizer-syncdaemon-logs:
    name: net-kidd-habitizer-syncdaemon-logs
